//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio2_DAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directores
    {
        public Directores()
        {
            this.Peliculas = new HashSet<Peliculas>();
        }
    
        public int id_director { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Peliculas> Peliculas { get; set; }
    }
}
