//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio2_DAS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModel_Movies2 : DbContext
    {
        public DbModel_Movies2()
            : base("name=DbModel_Movies2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Directores> Directores { get; set; }
        public DbSet<Generos> Generos { get; set; }
        public DbSet<Peliculas> Peliculas { get; set; }
        public DbSet<rate_per_user> rate_per_user { get; set; }
        public DbSet<rates> rates { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<Puntuaciones> Puntuaciones { get; set; }
    }
}
