//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio2_DAS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rates
    {
        public Nullable<int> id_pelicula { get; set; }
        public string titulo { get; set; }
        public Nullable<double> promedio_calificacion { get; set; }
        public int id_calificacion { get; set; }
    
        public virtual Peliculas Peliculas { get; set; }
    }
}
